version: "3"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - mqtt-network

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883" # MQTT port
      - "9001:9001" # WebSockets/WebSockets Secure port (optional)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    environment:
      MQTT_BROKER_HOST: "mosquitto" # Replace with the actual MQTT broker host
      MQTT_BROKER_PORT: 1883 # Replace with the actual MQTT broker port
    networks:
      - mqtt-network

  mqtt-publisher:
    build:
      context: ./mqtt-python/ # Build context path
      dockerfile: pub.Dockerfile  # Specify the Dockerfile to use
    container_name: mqtt-publisher
    environment:
      MQTT_BROKER_HOST: "mosquitto" # Replace with the actual MQTT broker host
      MQTT_BROKER_PORT: 1883 # Replace with the actual MQTT broker port
    networks:
      - mqtt-network
    depends_on:
      - mosquitto

  mqtt-subscriber:
    build:
      context: ./mqtt-python/ # Build context path
      dockerfile: sub.Dockerfile  # Specify the Dockerfile to use
    container_name: mqtt-subscriber
    environment:
      MQTT_BROKER_HOST: "mosquitto" # Replace with the actual MQTT broker host
      MQTT_BROKER_PORT: 1883 # Replace with the actual MQTT broker port
      MONGODB_URI: "mongodb://admin:password@mongodb:27017/" # Use the service name as the hostname
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
    networks:
      - mqtt-network
    depends_on:
      - mosquitto
      - mongodb
      - redis

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb-data:/data/db # Mount volume for MongoDB data
    networks:
      - mqtt-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb # Use the service name as the hostname
    networks:
      - mqtt-network
    depends_on:
      - mongodb

  fastapi-app:
    build:
      context: ./fast-api
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      MONGODB_URI: mongodb://admin:password@mongodb:27017/
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mqtt-subscriber
    networks:
      - mqtt-network

networks:
  mqtt-network:

volumes:
  mongodb-data:
  redis-data:
